### PR TITLE
Updates we made on our last call: full documentation of the template

### PR DESCRIPTION
**Pull request by cmaumet**
This PR includes all the changes recorded by @nicholst during our last call with @schw4b and myself.

### CODE REVIEW

**Comment by nicholst** [comment]
More work to do, but let's merge and move on...

**Comment by cmaumet** [comment]
@nicholst: it looks like you closed this PR without merging it. Is this what was intended? From your comment it sounds like you were going to merge?

**Comment by nicholst** [comment]
Ack!  Not intended.  Will fix.

**Comment by cmaumet** [comment]
Thank you!

**Pull request merged**
